---
- name: Create EC2 key pair in AWS
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  vars:
    region: ap-south-1
    key_name: aap-ec2-key
    private_key_path: /tmp/aap-ec2-key.pem

  tasks:
    - name: Create key pair in AWS
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        state: present
      register: ec2_key

    - name: Save private key locally
      copy:
        content: "{{ ec2_key.key.private_key }}"
        dest: "{{ private_key_path }}"
        mode: '0600'
      when: ec2_key.changed

    - name: Debug public key
      debug:
        msg: "Public key registered in AWS: {{ ec2_key.key.name }}"

    # - name: Debug private key path
    #   ansible.builtin.shell: "cat {{ private_key_path }}"
    #   register: private_key_content
    #   when: ec2_key.changed

    # - name: Show private key content
    #   debug:
    #     msg: "Private key saved at {{ private_key_path }}:\n{{ private_key_content.stdout }}"
    #   when: ec2_key.changed  

- name: Add AWS EC2 key to AAP
  hosts: localhost
  gather_facts: no
  vars:
    controller_host: "https://aap.example.org"
    controller_username: "admin"
    controller_password: "primod123"
    organization_id: 1                # ID of your org (use API/UI to confirm)
    private_key_file: "/tmp/aap-ec2-key.pem"

  tasks:
    - name: Read private key file
      slurp:
        src: "{{ private_key_file }}"
      register: private_key_content


    - name: Get activity stream logs
      ansible.builtin.uri:
        url: "{{ controller_host }}/api/controller//v2/credentials/"
        method: POST
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        force_basic_auth: yes
        validate_certs: false
        data:
          name: "AWS EC2 SSH Key"
          description: "SSH private key for AWS EC2 access"
          organization: "{{ organization_id }}"
          credential_type: Machine
          state: present   # 1 = Machine credential type
          inputs:
            username: ec2-user
            ssh_key_data: "{{ private_key_content['content'] | b64decode }}"

