---
# - name: check if we can attached credential to job template
#   hosts: localhost
#   gather_facts: no
#   collections:
#     - amazon.aws
#   vars:
#     region: ap-south-1
#     key_name: aap-ec2-key
#     private_key_path: /tmp/aap-ec2-key.pem
#     controller_host: "https://aap.example.org"
#     controller_username: "admin"
#     controller_password: "primod123"
#     organization_id: 1                # ID of your org (use API/UI to confirm)

- name: Attach credential declaratively
  hosts: localhost
  gather_facts: false
  collections:
    - infra.aap_configuration

  vars:
    #controller_hostname: "https://192.168.64.63"
    #controller_oauthtoken: "{{ token }}"
    aap_hostname: "https://192.168.64.63"
    aap_username: "admin"
    aap_password: "password"
    aap_validate_certs: false
    controller_validate_certs: false

    controller_templates:
      - name: CIS_Reporting
        organization: Default
        credentials:
          - "AWS EC2 SSH Key"

  roles:
    - infra.aap_configuration.controller_job_templates
